language: node_js
node_js:
  - node
env:
  - SERVER_IP_ADDRESS=157.245.40.180
before_install:
  - openssl aes-256-cbc -K $encrypted_77eaa0244e93_key -iv $encrypted_77eaa0244e93_iv
    -in id_rsa.enc -out ./id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./id_rsa
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./id_rsa
script:
  - bash scripts/test.sh
after_success:
  - bash scripts/deploy.sh
