version: "3"

services:
  frontend-intern:
    environment:
      - PUID=1000
      - PGID=1000
    container_name: frontend-intern
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik
    labels:
      - traefik.port = 80
      - traefik.http.routers.frontend-intern.rule=Host("fg.carosa.no")
      - traefik.http.routers.registry.service=frontend-intern
networks:
  traefik:
    external: true
